"""Seal only actual completed transport/strict/offserver evidence, never root-adopt."""
from pathlib import Path
import datetime,hashlib,json
H=Path(__file__).resolve().parent;R=H.parents[1]
F=Path('F:/YananResearchStorage/GuardFed')/H.name/'batch'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
read=lambda p:json.loads(Path(p).read_bytes())
def save(n,v):
 with (H/n).open('x',encoding='utf8',newline='\n') as f:json.dump(v,f,indent=2,ensure_ascii=False);f.write('\n')
a=read(H/'AUTHORIZED_SNAPSHOT.json');p=read(H/'OFFSERVER_ACCEPTANCE.json');receipt=read(F/'backup_receipt.json');strict=read(F/'ORIGINAL_STRICT.json');tensor=read(H/'SAVED_TENSOR_STATE_CHECK.json');released=read(H/'COLLECTOR_RELEASE.json')
ids=a['authorized_ids'];n=len(ids)
assert n==len(a['authorized_ids'])==3 and p['accepted_new_ids']==receipt['accepted_new_ids']==strict['accepted_new_ids']==ids
assert p['accepted_before']==39 and p['accepted_total']==42 and p['accepted_job_ids']==a['accepted_prior_ids']+ids
assert sha(R/a['prior_root_path'])==a['prior_root_sha256'] and sha(R/a['prior_offserver_path'])==a['prior_offserver_sha256']
assert p['previous_root_sha256']==a['prior_root_sha256'] and p['previous_offserver_sha256']==a['prior_offserver_sha256']
assert all(read(H/(name+'_COMMAND.json'))['exit_code']==0 for name in ['COLLECT','REMOTE_ARTIFACTS','SCP','VERIFY','RELEASE'])
assert p['status']=='OFFSERVER_ORIGINAL_STRICT_DELTA_PASS' and p['archive_verification']['pass'] and p['archive_verification']['different_host_observed']
assert p['members_verified']==receipt['members'] and p['archive_sha256']==sha(F/'gradient64_delta_after39_closed42.tar.gz')==receipt['archive_sha256']
assert p['original_strict_sha256']==sha(F/'ORIGINAL_STRICT.json')==receipt['original_strict_sha256']
assert p['new_inference']==p['new_training']==p['old_models_repacked']==0 and p['old39_ordered_prefix_exact']
assert [x['id'] for x in p['records']]==[x['id'] for x in tensor['records']]==ids and all(x['rounds']==70 for x in p['records'])
assert tensor['CNN_forward_calls']==tensor['optimizer_calls']==tensor['data_loads']==0 and released['CPU110_released']
assert released['guide_sha256']=='42be4f7a84349c7bca6f6b35c10e94d70ddeb9239bcdeaf0c56317d4ab3fd2aa'
assert not p['root_adopted'] and not p['method_champion_claim'] and not p['screen64_completed_claim']
raw=read(H/'RAW_STORAGE_INDEX.json')
for name,pin in raw['files'].items():assert sha(F/name)==pin['sha256'] and (F/name).stat().st_size==pin['bytes']
proof=dict(status='ROOT_READY_GRADIENT64_EXACT3_ORIGINAL_STRICT_OFFSERVER_PASS_NOT_ADOPTED',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),accepted_new_ids=ids,accepted_before=39,new_strict_offserver_count=n,strict_offserver_cumulative=42,root_accepted_cumulative_before_this_delivery=39,screen_total=64,all64_complete=False,archive_path=(F/'gradient64_delta_after39_closed42.tar.gz').as_posix(),archive_sha256=sha(F/'gradient64_delta_after39_closed42.tar.gz'),archive_bytes=(F/'gradient64_delta_after39_closed42.tar.gz').stat().st_size,archive_members=receipt['members'],receipt_path=(F/'backup_receipt.json').as_posix(),receipt_sha256=sha(F/'backup_receipt.json'),offserver_path=(H/'OFFSERVER_ACCEPTANCE.json').relative_to(R).as_posix(),offserver_sha256=sha(H/'OFFSERVER_ACCEPTANCE.json'),original_strict_sha256=sha(F/'ORIGINAL_STRICT.json'),inventory_sha256=p['inventory_sha256'],source_seal_sha256=p['scientific_package_sha256'],original_acceptor_sha256=p['original_validator_sha256'],prepared_source_seal_sha256=sha(H/'SOURCE_FILES_SHA256.json'),authorization_sha256=sha(H/'AUTHORIZED_SNAPSHOT.json'),snapshot_sha256=sha(H/'SNAPSHOT.json'),prior_root_path=a['prior_root_path'],prior_root_sha256=a['prior_root_sha256'],prior_offserver_path=a['prior_offserver_path'],prior_offserver_sha256=a['prior_offserver_sha256'],old39_ordered_prefix_exact=True,accepted_job_ids=p['accepted_job_ids'],records=p['records'],tensor_proof_sha256=sha(H/'SAVED_TENSOR_STATE_CHECK.json'),tensor_count=sum(x['tensor_count'] for x in tensor['records']),tensor_elements=sum(x['elements'] for x in tensor['records']),raw_storage_index_sha256=sha(H/'RAW_STORAGE_INDEX.json'),F_raw_storage_root=F.as_posix(),CPU110_released=True,resource_release_sha256=sha(H/'COLLECTOR_RELEASE.json'),source_data_rehashed_before_after=True,original_scientific_acceptor_unchanged=True,local_runtime=p['local_runtime'],runtime_equivalence_claim=False,shared_logs_are_prefixes_only=True,prediction_arrays_recomputed=False,negative_and_constant_results_retained=True,auxiliary_snapshot_schema_failure_preserved=False,science_or_transport_retried=False,new_CNN=0,new_training=0,test=False,recipe_selection_performed=False,root_adoption_required=True,LATEST_STATE_Git_unchanged=True)
save('ROOT_READY_HANDOFF.json',proof)
save('ROOT_READY_CHAIN_LINK.json',dict(status='ROOT_PENDING_GRADIENT64_RECOVERY_CHAIN_LINK',previous_root_path=a['prior_root_path'],previous_root_sha256=a['prior_root_sha256'],previous_offserver_path=a['prior_offserver_path'],previous_offserver_sha256=a['prior_offserver_sha256'],accepted_before=39,accepted_new=n,accepted_total=42,accepted_job_ids=p['accepted_job_ids'],new_ids=ids,next_previous_offserver_path=proof['offserver_path'],next_previous_offserver_sha256=proof['offserver_sha256'],archive_path=proof['archive_path'],archive_sha256=proof['archive_sha256'],receipt_path=proof['receipt_path'],receipt_sha256=proof['receipt_sha256'],handoff_sha256=sha(H/'ROOT_READY_HANDOFF.json'),root_adoption_required=True,source_package_sha256=p['scientific_package_sha256']))
with (H/'README.md').open('x',encoding='utf8',newline='\n') as f:f.write('# Actual gradient64 exact3 delta — root adoption pending\n\nOne actual v2a snapshot fixed 42 terminal jobs minus the root-adopted accepted39; the exact delta comprises three Huber records. The exact new3 passed original checked_result remotely and locally, original v4 archive/member verification and unchanged saved fullstate layout/dtype/finiteness. Actual cumulative strict/offserver42/64 is not root adoption or completed search; no recipe was selected.\n\nOnly predecessor schema/pins/counts, a fresh namespace/archive and explicit parent-task authorization were rebound in the after1 transport. Original scientific acceptor, original shared input binding, original model checks and archive verifier are unchanged. Previous39 models were not repackaged; all outcomes, including constant predictions, are preserved. Shared live logs are bounded prefixes, not closed per-job logs. All raw/model/archive/restored bulk went directly to freshly checked healthy Yanan 2TB F with required+reserve guard; no internal fallback.\n\nLocal CPU Torch differs from server cu128; no runtime equivalence is claimed. No CNN forward, optimizer, fitting, training, data loading, test or prediction recomputation occurred. CPU110 released. Later queue completions excluded. LATEST/STATE/Git/source/service unchanged. Root must separately adopt this batch.\n')
files={p.relative_to(H).as_posix():dict(sha256=sha(p),bytes=p.stat().st_size) for p in sorted(H.rglob('*')) if p.is_file() and '__pycache__' not in p.parts}
save('DELIVERY_FILES_SHA256.json',dict(status='ACTUAL_GRADIENT64_DELTA_PASS_ROOT_PENDING',files=files,raw_storage_index_sha256=sha(H/'RAW_STORAGE_INDEX.json'),root_adoption_performed=False))
print(json.dumps(dict(new=n,total=42,members=receipt['members'],archive_sha256=proof['archive_sha256'],handoff_sha256=sha(H/'ROOT_READY_HANDOFF.json'),chain_sha256=sha(H/'ROOT_READY_CHAIN_LINK.json'),seal_sha256=sha(H/'DELIVERY_FILES_SHA256.json'),files=len(files))))
