from pathlib import Path
import datetime,hashlib,json
H=Path(__file__).resolve().parent;R=H.parents[1];B=R/'tmp/celeba_flgmm_fullcoverage_incremental_20261009'
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads(p.read_bytes())
def save(p,v):
 with p.open('x',encoding='utf8') as f:json.dump(v,f,indent=2);f.write('\n')
auth=read(H/'AUTHORIZED_SNAPSHOT.json');prior=read(H/'PREVIOUS_OFFSERVER_ACCEPTANCE.json');latest=read(H/'PREVIOUS_LATEST.json');proof=read(H/'batch/OFFSERVER_ACCEPTANCE.json');receipt=read(H/'batch/BACKUP_SHA256.json');server=read(H/'batch/PARTIAL_ACCEPTANCE.json');snap=read(H/'batch/restored/live_snapshot.json');tensor=read(H/'SAVED_TENSOR_STATE_CHECK.json');closed=read(H/'COLLECTOR_CLOSED.json')
assert all(read(H/name)['exit_code']==0 for name in ('PREFLIGHT_COMMAND.json','DISPATCH_RECEIPT.json','SCP_RECEIPT.json','VERIFY_COMMAND.json','COLLECTOR_CLOSED_COMMAND.json'))
assert sha(B/'LATEST_BACKUP.json')==sha(H/'PREVIOUS_LATEST.json') and read(B/'LATEST_BACKUP.json')==latest
assert sha(R/latest['root_adoption_path'])==auth['prior_root_sha256']
assert sha(H/'PREVIOUS_OFFSERVER_ACCEPTANCE.json')==receipt['previous_chain_sha256']==auth['prior_offserver_sha256']=='83bca8eef7ed5423315ad5bef4b42ccd0335bb750c4214f2e50abcd2db9e8e34'
assert prior['accepted_total']==12 and proof['accepted_new']==2 and proof['accepted_total']==14
assert proof['accepted_job_ids'][:12]==prior['accepted_job_ids'] and len(set(proof['accepted_job_ids']))==14
assert proof['new_ids']==receipt['accepted_new_ids']==auth['authorized_ids'] and set(proof['accepted_job_ids'])-set(prior['accepted_job_ids'])==set(auth['authorized_ids'])
assert proof['package_sha256']==auth['source_hashes']['PACKAGE_SHA256.json']=='6200c40f22a8ea670cfa02f0e74bbd81dc4ef9adecc258f979ddacc078a5d230'
assert server['before_source_data']==server['after_source_data'] and server['helper_cpu']==107 and server['helper_threads']==1 and server['helper_nice']==10
assert receipt['archived_member_count']==27 and sha(H/'batch/accepted_delta.tar.gz')==receipt['archive_sha256']
assert tensor['CNN_forward_calls']==tensor['optimizer_calls']==tensor['data_loads']==0 and [r['id'] for r in tensor['records']]==proof['new_ids']
assert closed['CPU107_released'] and not closed['queue']['failed']
assert sha(B/'FILES_SHA256.json')=='f6de59a56de25a8d316cf7e05c44eafc9751041757e4dc61c88f7bccfd988472'
for n,p in read(B/'FILES_SHA256.json')['files'].items():assert sha(B/n)==p['sha256']
assert sha(H/'verify_delta_offserver.py')==sha(B/'verify_delta_offserver.py')=='ecb6627ab90aafa667795d2b3146f6b67abb1924462534640fc31b5dc7b7edfe'
reuse=read(H/'SOURCE_REUSE.json');actual=(H/'collect_delta.py').read_text(encoding='utf8');addition='    # Parent-authorized fixed snapshot exact2 only; later terminal IDs remain unaccepted.\n    authorized_ids='+repr(auth['authorized_ids'])+'\n    wanted=[identity for identity in wanted if identity in authorized_ids]\n'
assert actual.replace(addition,'')==(B/'collect_delta.py').read_text(encoding='utf8')
ready=dict(status='ROOT_READY_FL96_INCREMENT_STRICT_OFFSERVER_PASS_NOT_ADOPTED',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),accepted_new_ids=proof['new_ids'],prior_accepted_new=12,accepted_new=2,accepted_new_cumulative=14,planned_new=96,separately_reused70round=4,planned_total=100,single_fixed_authorization_snapshot=True,authorization_sha256=sha(H/'AUTHORIZED_SNAPSHOT.json'),actual_collector_snapshot_utc=snap['utc'],actual_collector_snapshot_sha256=sha(H/'batch/restored/live_snapshot.json'),source_package_sha256=proof['package_sha256'],original_helper_seal_sha256=sha(B/'FILES_SHA256.json'),collector_sha256=sha(H/'collect_delta.py'),collector_scope_diff_sha256=sha(H/'COLLECTOR_SCOPE_DIFF.patch'),verifier_sha256=sha(H/'verify_delta_offserver.py'),offserver_acceptance_path=(H/'batch/OFFSERVER_ACCEPTANCE.json').relative_to(R).as_posix(),offserver_acceptance_sha256=sha(H/'batch/OFFSERVER_ACCEPTANCE.json'),archive_path=(H/'batch/accepted_delta.tar.gz').relative_to(R).as_posix(),archive_sha256=receipt['archive_sha256'],archive_bytes=receipt['archive_size'],archive_members=receipt['archived_member_count'],member_manifest_path=(H/'batch/MEMBERS.json').relative_to(R).as_posix(),inventory_sha256=receipt['inventory_sha256'],server_backup_receipt_sha256=sha(H/'batch/BACKUP_SHA256.json'),server_strict_sha256=receipt['acceptance_sha256'],previous_root_path=latest['root_adoption_path'],previous_root_sha256=latest['root_adoption_sha256'],previous_actual_offserver_sha256=receipt['previous_chain_sha256'],previous_latest_sha256=sha(H/'PREVIOUS_LATEST.json'),old12_ordered_prefix_exact=True,original_strict_and_archive_body_unchanged=True,full_saved_tensor_check_sha256=sha(H/'SAVED_TENSOR_STATE_CHECK.json'),tensor_count=16,tensor_elements=187012,records=proof['records'],source_data_before_after_exact=True,helper_CPU=107,helper_threads=1,nice=10,IO='idle',server_verification_runtime=server['acceptance_runtime'],local_verification_runtime=proof['verification_runtime'],resource_preflight_sha256=sha(H/'PREFLIGHT.json'),resource_after_sha256=sha(H/'COLLECTOR_CLOSED.json'),CPU107_released=True,no_old_models_repacked=True,CNN_forward_calls=0,training_calls=0,final_test=False,recipe_selection_performed=False,root_adoption_required=True,LATEST_STATE_Git_unchanged=True,scientific_complete=False)
save(H/'ROOT_READY_HANDOFF.json',ready)
save(H/'ROOT_READY_CHAIN_LINK.json',dict(status='ROOT_REVIEW_PENDING_CHAIN_LINK_NO_CANONICAL_WRITE',previous_latest_path=B.relative_to(R).as_posix()+'/LATEST_BACKUP.json',previous_latest_sha256=sha(H/'PREVIOUS_LATEST.json'),previous_root_path=latest['root_adoption_path'],previous_root_sha256=latest['root_adoption_sha256'],previous_offserver_path=latest['next_collector_previous_path'],previous_offserver_sha256=receipt['previous_chain_sha256'],proposed_next_collector_previous_path=ready['offserver_acceptance_path'],proposed_next_collector_previous_sha256=ready['offserver_acceptance_sha256'],accepted_before=12,accepted_new=2,accepted_total=14,accepted_job_ids=proof['accepted_job_ids'],new_ids=proof['new_ids'],archive_sha256=receipt['archive_sha256'],member_manifest_sha256=receipt['inventory_sha256'],source_package_sha256=proof['package_sha256'],handoff_sha256=sha(H/'ROOT_READY_HANDOFF.json'),old12_ordered_prefix_exact=True,reused4_repacked=False,root_adoption_required=True))
files={p.relative_to(H).as_posix():dict(sha256=sha(p),bytes=p.stat().st_size) for p in sorted(H.rglob('*')) if p.is_file() and 'restored' not in p.relative_to(H).parts and '__pycache__' not in p.parts}
save(H/'DELIVERY_FILES_SHA256.json',dict(status='ACTUAL_INCREMENT_OFFSERVER_PASS_ROOT_PENDING',files=files,derived_restored_tree_excluded=True,root_adoption_not_performed=True))
print(json.dumps(dict(accepted_new=2,total_new=14,archive_sha256=ready['archive_sha256'],members=27,handoff_sha256=sha(H/'ROOT_READY_HANDOFF.json'),chain_link_sha256=sha(H/'ROOT_READY_CHAIN_LINK.json'),delivery_seal_sha256=sha(H/'DELIVERY_FILES_SHA256.json'),files=len(files))))
