[program:guardfed_celeba_hybrid_cuda_gate]
environment=PROC_NAME="%(program_name)s"
command=/opt/supervisor-scripts/guardfed_celeba_hybrid_cuda_gate.sh
autostart=false
autorestart=false
startsecs=0
startretries=0
stopasgroup=true
killasgroup=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
redirect_stderr=true
