from pathlib import Path
import ast,datetime,hashlib,json,math,os,statistics,subprocess,sys
sys.dont_write_bytecode=True
os.environ.update(CUDA_VISIBLE_DEVICES='',OMP_NUM_THREADS='1',MKL_NUM_THREADS='1',OPENBLAS_NUM_THREADS='1')
H=Path(__file__).resolve().parent; R=H.parents[1]
F=Path('F:/YananResearchStorage/GuardFed/hybrid_native_after1_20261011');V=F/'verified';S=V/'stage'
sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
read=lambda p:json.loads(Path(p).read_bytes())
def save(n,v):
 with (H/n).open('x',encoding='utf8',newline='\n') as f:json.dump(v,f,indent=2);f.write('\n')
def copy(p,n):
 with (H/n).open('xb') as f:f.write(p.read_bytes())
assert sha(H/'FILES_SHA256.json')=='32c45838444f673ccecc7424f5f541a3e23e308c2e0a917e2129fd319b2634c3'
for n,p in read(H/'FILES_SHA256.json')['files'].items():assert sha(H/n)==p['sha256']
delta=read(H/'DELTA_SCOPE.json');IDS=delta['ids'];off=read(V/'OFFSERVER_VERIFICATION.json');receipt=read(F/'BACKUP_RECEIPT.json');remote=read(F/'REMOTE_STRICT.json')
assert off['status']=='PASS_FULL_MEMBER_SHA_AND_ORIGINAL_SAVED_COMPARISON' and (off['accepted_total'],off['local']['accepted_before'],off['local']['accepted_new'],off['member_count'])==(9,1,8,272)
assert off['local']['accepted_new_ids']==IDS and off['archive_sha256']==sha(F/'delta.tar.gz')==receipt['archive_sha256']
assert remote['source_data_before']==remote['source_data_after'] and remote['server_runtime']['CPU']==[108]
for n in ['COLLECT','SCP','RESTORE_VERIFY']:assert read(H/(n+'_COMMAND.json'))['returncode']==0
release=read(H/'CPU_RELEASE.json');assert release['CPU108_released']
records=read(H/'RECORDS8.json')['records'];assert [x['id'] for x in records]==IDS
assert read(H/'SAVED_TENSOR_IDENTITY.json')['tensors']==64
manifest=read(S/'manifest.json')
# Ten distinct seed identities: original accepted selected screen1 + accepted formal1 + this exact8.
reuse=next(x for x in manifest['reused_jobs'] if (x['distribution'],x['attack'],x['seed'])==('IID','Benign',91001))['accepted_record']
summary=R/'tmp/celeba_hybrid32_final_collection_20261010/SUMMARY32.json';bound=read(H/'ROOT_BOUND_ADOPTION.json')
assert sha(summary)==bound['summary_sha256']=='46b5f8fdca9536166ed868e50d4c7bc2578f8a1100ffea97878cf044c95748ae'
winner=next(x for x in read(summary)['all_candidates'] if x['candidate']==bound['selected_recipe']['id'])
summary_record=next(x for x in winner['records'] if x['id']==reuse['id'])
assert set(summary_record)=={'id','candidate','distribution','attack','seed','metrics','checkpoint_sha256','acceptance_sha256'}
assert {k:reuse[k] for k in summary_record}==summary_record and reuse['rounds']==70
reuse_entry=next(x for x in manifest['reused_jobs'] if x['id']==reuse['id'])
assert reuse_entry['job_sha256']==reuse['job_sha256'] # Reuse job is root-bound manifest metadata;old file intentionally not repacked.
assert all(remote['source_data_before'][k]==v for k,v in reuse['source_hashes'].items())
prior=read(H/'PRIOR_ROOT_ADOPTION.json');ten=[dict(reuse,source='ORIGINAL_SELECTED_SCREEN_REUSE',root32_sha256=bound['root32_sha256']),dict(id=prior['accepted_new_ids'][0],seed=91002,metrics=prior['metrics'],checkpoint_sha256=prior['checkpoint_sha256'],source='PRIOR_ROOT_ADOPTED_FORMAL1')]+[dict(id=x['id'],seed=x['seed'],metrics=x['metrics'],checkpoint_sha256=x['checkpoint_sha256'],source='THIS_EXACT8_ROOT_ADOPTION_PENDING') for x in records]
assert [x['seed'] for x in ten]==list(range(91001,91011)) and len({x['id'] for x in ten})==10
stats={k:dict(mean=statistics.mean(x['metrics'][k] for x in ten),sample_SD=statistics.stdev(x['metrics'][k] for x in ten),n=10,ddof=1) for k in ['accuracy','aeod','aspd']}
save('IID_BENIGN10_NATIVE.json',dict(status='DESCRIPTIVE_TEN_SEED_NATIVE_ORIGINAL_RECORDS_EXACT8_ROOT_ADOPTION_PENDING',records=ten,statistics=stats,source_summary_path=summary.relative_to(R).as_posix(),source_summary_sha256=sha(summary),root_bound_sha256=sha(H/'ROOT_BOUND_ADOPTION.json'),new_formal_records=9,reused_screen_records=1,unit='all metrics fraction;ACC multiplied100 only in Markdown',selection_history='Seed91001 is one of four original valid-only search conditions used to select the fixed recipe; nine other seeds are formal coverage. Post-initial-test development history retained; no new finaltest.',all_negative_results_retained=True,not_full100=True,not_significance_or_causal=True))
md=['# Hybrid: first complete IID / Benign native scene','', 'AUTHOR_REVIEW / ROOT_ADOPTION_PENDING_EXACT8. Ten seeds = original selected screen reuse91001 + prior root-adopted formal91002 + this batch91003–91010. This is one scene, not100 completion or finaltest. Native terminal argmax only; no saved prediction arrays were supplied/recomputed.','', '| n | ACC (%) mean ± sample SD | AEOD mean ± sample SD | ASPD mean ± sample SD |','|---:|---:|---:|---:|',f"| 10 | {stats['accuracy']['mean']*100:.6f} ± {stats['accuracy']['sample_SD']*100:.6f} | {stats['aeod']['mean']:.8f} ± {stats['aeod']['sample_SD']:.8f} | {stats['aspd']['mean']:.8f} ± {stats['aspd']['sample_SD']:.8f} |",'', 'All ten records and their checkpoints are listed in IID_BENIGN10_NATIVE.json. The fixed recipe was selected on exposed valid search data;seed91001 participates in selection. No reselection, significance or necessity claim. Training was original cu128/GPU0; server saved checks use cu128 CPU tensors, local saved checks use Windows torch2.8.0+cpu. Metadata bridges do not establish numerical-environment equivalence.']
(H/'IID_BENIGN10_NATIVE.md').write_text('\n'.join(md)+'\n',encoding='utf8',newline='\n')
files=[p for p in sorted(F.rglob('*')) if p.is_file()]
save('RAW_STORAGE_INDEX.json',dict(status='F_ONLY_NEW_EXACT8_ARCHIVE_RECOVERY_INDEX',bulk_root=F.as_posix(),files={p.relative_to(F).as_posix():dict(path=p.as_posix(),sha256=sha(p),bytes=p.stat().st_size) for p in files},original_F_guard=read(H/'F_VOLUME_DOWNLOAD.json'),prior_models_repacked=0,reuse_models_repacked=0))
handoff=dict(status='ROOT_READY_EXACT8_HYBRID70_NATIVE_STRICT_OFFSERVER_NOT_ADOPTED',utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),accepted_before=1,accepted_new=8,accepted_total=9,accepted_new_ids=IDS,accepted_ids=off['accepted_ids'],planned_new=96,reused_separate=4,planned_total=100,first_complete_scene='IID / Benign / 10seed = reuse1+formal9',root_adopted=False,root_adoption_required=True,prior_root_path='tmp/celeba_hybrid_first1_root_adoption_20261010/ROOT_ADOPTION.json',prior_root_sha256=sha(H/'PRIOR_ROOT_ADOPTION.json'),prior_offserver_sha256=sha(H/'PRIOR_OFFSERVER.json'),archive_path=(F/'delta.tar.gz').as_posix(),archive_sha256=sha(F/'delta.tar.gz'),archive_bytes=(F/'delta.tar.gz').stat().st_size,archive_members=off['member_count'],receipt_path=(F/'BACKUP_RECEIPT.json').as_posix(),receipt_sha256=sha(F/'BACKUP_RECEIPT.json'),inventory_sha256=receipt['inventory_sha256'],offserver_path=(V/'OFFSERVER_VERIFICATION.json').as_posix(),offserver_sha256=sha(V/'OFFSERVER_VERIFICATION.json'),remote_strict_sha256=sha(F/'REMOTE_STRICT.json'),source_seal_sha256=sha(H/'FILES_SHA256.json'),delta_scope_sha256=sha(H/'DELTA_SCOPE.json'),package_sha256=receipt['package_sha256'],original_checked_source_sha256=remote['original_checked_source_sha256'],source_data_before_after_exact=True,same_terminal_checkpoint_all_metrics=True,rounds=70,n_eval=19867,saved_models=8,saved_tensors=64,tensor_proof_sha256=sha(H/'SAVED_TENSOR_IDENTITY.json'),raw_storage_index_sha256=sha(H/'RAW_STORAGE_INDEX.json'),server_runtime=remote['server_runtime'],local_runtime=off['local']['local_verification_runtime'],runtime_equivalence_claim=False,CPU108_released=release['CPU108_released'],release_sha256=sha(H/'CPU_RELEASE.json'),collector_runs=1,restore_runs=1,actual_exit_codes={n:read(H/(n+'_COMMAND.json'))['returncode'] for n in ['COLLECT','SCP','RESTORE_VERIFY','CPU_RELEASE']},new_CNN=0,new_fit=0,new_training=0,final_test=False,recipe_reselection=False,prediction_arrays_supplied=False,prediction_arrays_recomputed=False,negative_results_preserved=True,shared_STATE_LATEST_Git_changed=False,preparation_failure_preserved='PREPARATION_FAILURE_001.json',limitations=['One complete IID Benign scene only;remaining full100 not complete.','Tensor and saved-record checks only;no numerical cross-runtime equivalence or prediction-array replay.','Reuse91001 is original exposed-valid selected screen record;not a fresh independently selected seed.','This exact8 requires independent root adoption;prior1/reuse4 remain separate and unrepacked.'])
save('ROOT_READY_HANDOFF.json',handoff)
save('ROOT_READY_CHAIN_LINK.json',dict(status='EXACT8_ROOT_ADOPTION_PENDING',accepted_before=1,accepted_new=8,accepted_total=9,accepted_ids=off['accepted_ids'],previous_offserver_sha256=sha(H/'PRIOR_OFFSERVER.json'),previous_root_sha256=sha(H/'PRIOR_ROOT_ADOPTION.json'),next_prior_offserver_path=(V/'OFFSERVER_VERIFICATION.json').as_posix(),next_prior_offserver_sha256=sha(V/'OFFSERVER_VERIFICATION.json'),handoff_sha256=sha(H/'ROOT_READY_HANDOFF.json'),root_adoption_required=True,reused_separate=4))
save('DELIVERY_FILES_SHA256.json',dict(status='ACTUAL_COMPACT_EXACT8_ROOT_READY_DELIVERY',files={p.name:dict(sha256=sha(p),bytes=p.stat().st_size) for p in sorted(H.iterdir()) if p.is_file()}))
print(json.dumps(dict(handoff_sha256=sha(H/'ROOT_READY_HANDOFF.json'),delivery_seal_sha256=sha(H/'DELIVERY_FILES_SHA256.json'),delivery_members=len(read(H/'DELIVERY_FILES_SHA256.json')['files']),offserver_sha256=sha(V/'OFFSERVER_VERIFICATION.json'),archive_sha256=sha(F/'delta.tar.gz'),new8=IDS,total_new9=True,CPU108_released=True,statistics=stats),indent=2))
